# Generated by Django 3.2.6 on 2021-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hming', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('domain', models.CharField(blank=True, max_length=30, null=True)),
                ('types', models.TextField(max_length=300)),
            ],
        ),
    ]
